# #############################################################
# set workdirection; library package
setwd('F:\\jTKount\\1201\\白相  1220  广义线性回归 stata   ☆')
library(readxl)
library(car)
library(xtable)
library(flextable)
library(officer)
library(dplyr)
library(reshape2)
library(ggplot2)
library(psych)
# #############################################################
# input datas; add colnames
dat_44<-read_excel('MSDtaste.xlsx', sheet = 1,col_names = T)
data_u<-data.frame(dat_44)
data_u1<-na.omit(data_u)
# 1 单因素方差分析 
col_ = c('count', 'duration', 'keySignature', 'popularity',
         'energy', 'loudness', 'tempo', 'timeSignature')
doc = read_docx()
for(col in col_){
  # levene test
  lvT<-leveneTest(as.numeric(unlist(data_u1[col])), as.factor(data_u1$mode))
  word_lvt = xtable_to_flextable(xtable(lvT))
  doc = body_add_flextable(doc, word_lvt)
}
print(doc, 'leveneTest.docx')
# one way test
doc = read_docx()
owt<-oneway.test(count~mode, data=data_u1, var.equal = TRUE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(duration~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(keySignature~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(popularity~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(energy~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(loudness~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(tempo~mode, data=data_u1, var.equal = TRUE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
owt<-oneway.test(timeSignature~mode, data=data_u1, var.equal = FALSE)
df_owt<-data.frame(owt$statistic,owt$parameter[1],owt$parameter[2],owt$p.value)
word_owt<-xtable_to_flextable(xtable(df_owt))
doc = body_add_flextable(doc, word_owt)
print(doc, 'onewayTest.docx')
# split and describe
doc = read_docx()
col_gb<-c('duration','keySignature', 'popularity', 
          'energy', 'loudness', 'tempo', 'timeSignature')
data_ug<-split(data_u1,data_u1['mode'])
delay0 <- describe(data_ug$`0`[col_gb])
word_delay<-xtable_to_flextable(xtable(delay0))
doc = body_add_flextable(doc, word_delay)
delay1 <- describe(data_ug$`1`[col_gb])
word_delay<-xtable_to_flextable(xtable(delay1))
doc = body_add_flextable(doc, word_delay)
print(doc, 'groupby&describe.docx')
data_u1_m<-melt(data_u1, id.vars = 'mode', measure.vars=col_gb, variable.name='variable')
data_u1_m$mode<-as.factor(data_u1_m$mode)
ggplot(data=data_u1_m, aes(x=mode, y=value))+geom_boxplot(aes(fill=variable))+facet_wrap(~variable, scales = 'free')

col_gb1<-c('duration','keySignature', 'popularity', 'energy', 
           'mode','loudness', 'tempo', 'timeSignature', 'year')
data_u1_m1<-melt(data_u1, id.vars = 'count', measure.vars = col_gb1, variable.name = 'variable')
ggplot(data=data_u1_m1)+geom_point(aes(x=value, y=count, color=as.factor(variable)))+facet_wrap(~variable, scales = 'free')
# glm model
doc = read_docx()
g<- glm(count~duration+keySignature+popularity+energy+mode+loudness+tempo+timeSignature+year, data = data_u1,
    family = poisson(),control = list(maxit = 100))
g.sum<-summary(g)
l <- lm(count~duration+keySignature+popularity+energy+mode+loudness+tempo+timeSignature+year, data = data_u1)
l.sum <- summary(l)
word_glm<-xtable_to_flextable(xtable(g.sum))
doc = body_add_flextable(doc, word_glm)
print(doc, 'glmsum.docx')